### ISSUE TITLE
No Access to Feature packs and Other links

### ISSUE THREAD

**Issue by khoa798** [Adobe-Marketing-Cloud/aem-screens-howto#1]
Hi,
I am unable to access the various links so that I can gain more info from these feature packs or to download the provided files. I am currently interning at a company that wishes to fully utilize AEM Screens and I'd love to get access to these links so I could learn more!

To be more precise I get:
This site can’t provide a secure connection
git.corp.adobe.com didn’t accept your login certificate, or one may not have been provided.
Try contacting the system admin.
ERR_BAD_SSL_CLIENT_AUTH_CERT

**To Reproduce**
1. Go to repo
2. Click on any of the available links with an unverified account.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 67.0.3396.99
--

**Comment by ramboz** [comment]
@khoa798 Thanks for reporting the issue.

I fixed the links for the Screens FP (note that 6.4 Screens FP1 is not yet public on package share, but should be in a few days). I also fixed the link to the releases.

**Comment by ramboz** [comment]
In the meantime feel from to browse through the documentation at https://helpx.adobe.com/experience-manager/6-4/screens/user-guide.html

**Comment by khoa798** [comment]
Hi @ramboz 

I appreciate the prompt response! Thank you for your hard work !

Regards,
Khoa Hoang
